### ISSUE TITLE
GPU如何调整？

### ISSUE THREAD

**Issue by wulongjian** [ZF1044404254/TBMSL-Net#1]
您好，请问一下如果有两张GPU卡，需要调整的地方是在` config.py` 中的 `CUDA_VISIBLE_DEVICES = '0'`  改为 `CUDA_VISIBLE_DEVICES = '0,1'` 就可以了吗？ 
还有关于 N_list的三个参数，请问16g的显存，对于CUB数据集，应调整为多少合适？
十分感谢您的回复

**Comment by ZF1044404254** [comment]
@wulongjian 你好，我的实验环境是单卡p100 `16G，不知双卡是否存在bug，如你所说**CUDA_VISIBLE_DEVICES = '0,1'**，即可启用双卡。至于N_list，是我经过多次尝试确定的，16G显存完全够用。`

**Comment by wulongjian** [comment]
谢谢您的回答。我尝试了设置`CUDA_VISIBLE_DEVICES = '0,1'`，但在运行时显示只调用了gpu0,您的代码似乎并没有关于并行训练的调整，不过单张卡也可以训练，只是batch_size要调整为3或者更小。
