### ISSUE TITLE
你好！关于AOLM部分

### ISSUE THREAD

**Issue by IItaly** [ZF1044404254/TBMSL-Net#36]
请问：
AOLM中获取左上和右下的坐标值时的*32是为什么？
以及如何避免取坐标后local_image为一条线的情况？

**Comment by yunmi02** [comment]
因为特征图缩小了32倍，所以通过14*14特征图找到的坐标要*32还原到原图片中。

**Comment by yunmi02** [comment]
因为特征图最后一层的特征图是14*14的相较于输入图片缩小了32倍，所以通过14*14特征图找到的坐标要*32倍才能还原到原图中的对应坐标。

**Comment by IItaly** [comment]
> 因为特征图最后一层的特征图是14_14的相较于输入图片缩小了32倍，所以通过14_14特征图找到的坐标要*32倍才能还原到原图中的对应坐标。

谢谢！
