### ISSUE TITLE
Another N_list config [for speed up training]

### ISSUE THREAD

**Issue by ahkarami** [ZF1044404254/TBMSL-Net#4]
@ZF1044404254,
Thank you very much for your great work. 
Can you please introduce another configuration for `N_list` (for CAR data set) that will increase the speed of training? 
(Do we need to change `window_side` & `ratios`?)

**Comment by ZF1044404254** [comment]
@ahkarami 
Hi, of course, you can reduce `N1, N2, N3` of `N_list` which can improve the training speed a little, but the accuracy may also be impaired. As for `window_side` is related to the depth of the network, so for the currently used backbone (resnet-50), `window_side` is 32; `ratios` is the aspect ratio of each window, you can try to increase or decrease the number of proportions (`ratios`), maybe make the accuracy there is improvement. `N_list` and `ratios` are hyperparameters, which can be determined through a lot of experiments.

**Comment by ahkarami** [comment]
Thank you very much for your useful comment.
